### ISSUE TITLE
bug: success event did not call

### ISSUE THREAD

**Issue by expcapitaldev** [trustly/cordova-plugin-trustly-checkout#2]
iOS,Android

after successful deposit, trustly activity cannot be closed and promise can no be resolved never. How we can close activity and returned to the app ? 
- called never https://github.com/trustly/cordova-plugin-trustly-checkout/blob/main/src/android/com/trustly/sdk/TrustlyJavascriptInterface.java#L84

if you implemented for example 
- for android: https://github.com/expcapitaldev/cordova-plugin-trustly/blob/2.0.0/src/android/com/expcapital/trustly/TrustlyActivity.java#L45
- for ios:  https://github.com/expcapitaldev/cordova-plugin-trustly/blob/2.0.0/src/ios/CDVTrustlyWKWebView.swift#L79

we can understand success Url/failed Url and close activity and returned to the main app

**Comment by Macksen** [comment]
Hi, 
Is the following successUrl callback not fired when finishing an order?

<img width="650" alt="Screenshot 2021-07-20 at 13 32 11" src="https://user-images.githubusercontent.com/7474719/126317100-97ab40f2-8d3a-4c2c-9ee3-6e663c1cfa85.png">

I tried this out myself and was able to receive both ABORT and SUCCESS events, are you using your own solution for this or using this lib to implement the SDK?

**Comment by expcapitaldev** [comment]
@Macksen I used your SDK plugin, with abort worked - catch block, but with successurl - did not work

**Comment by Macksen** [comment]
@expcapitaldev Are you able to show me your implementation?

**Comment by expcapitaldev** [comment]
@Macksen 
but, I debugged native code on ios/android, and onTrustlyCheckoutSuccessfull did not triggered
window.trustly.showTrustlyCheckout(checkoutUrl)
						.then((successUrl: string) => {
                                                                  this.logger.log('successUrl ' + successUrl);
								resolve(successUrl);
						})
						.catch((err: ITrustlyCheckoutPluginError) => {
								this.logger.warn('error ' + JSON.stringify(err));
								reject(err);
						});

**Comment by Macksen** [comment]
@expcapitaldev I am a bit unsure as to why this occurs, looking at the SDK it runs through the same logic as with the abort call with no special cases. I am not able to reproduce this myself, when exactly is it that you're expecting this SUCCESS event, is it after the user is done with an order altogether?

**Comment by Macksen** [comment]
@expcapitaldev Do you perhaps have an OrderID you can share with me?

**Comment by expcapitaldev** [comment]
@Macksen  yes, after the user is done with an order altogether. When promise should be resolved?

**Comment by expcapitaldev** [comment]
@Macksen OrderID=14894799344

**Comment by expcapitaldev** [comment]
@Macksen  pls send video with your deposit

**Comment by Macksen** [comment]
Here's a test video:

https://user-images.githubusercontent.com/7474719/126500687-78369c7e-2aa2-443e-87ea-3d60edbf3b43.mov

**Comment by expcapitaldev** [comment]
@Macksen I can send on your email my test apk for example

**Comment by expcapitaldev** [comment]
@Macksen  you can from window call. trustly checkout and check

**Comment by Macksen** [comment]
I am getting the same isssue on android, I am looking into it.

**Comment by expcapitaldev** [comment]
https://github.com/trustly/cordova-plugin-trustly-checkout/blob/eb10d7151c88cdd0a57e604eb911afa3586011e7/src/android/com/trustly/sdk/TrustlyActivity.java#L35 ?

**Comment by Macksen** [comment]
Yeah, it's empty for some reason, not handling any response, I am waiting to push a code change

**Comment by Macksen** [comment]
Can you see if you're getting an event now if you pull the latest changes? I.e, reinstall the plugin

**Comment by expcapitaldev** [comment]
@Macksen  I updated with your last commit for android. So, after successfull/ or abort I see my success/fail URL, but trustly activity closed, and only after go back (android back button) I see my app again (browser page closed) but I see abort only type.
After that I removed my success/fail URL and check again
see screenshots after successful deposit
![photo_2021-07-23 17 48 11](https://user-images.githubusercontent.com/19390317/126799642-d8abe8c2-fcad-4e7c-8346-4bd4b2e24e6c.jpeg)

**Comment by rhorno** [comment]
Hi @expcapitaldev, as I understand the initial problem with you not getting the success event is fixed now, right?
Are you having another problem after the events now? Is it only on android?

**Comment by expcapitaldev** [comment]
@rhorno  @Macksen  No, the problem is still relevant.
I will try to send more info tomorrow

**Comment by expcapitaldev** [comment]
@Macksen @rhorno  pls describe step by step , when trustly activity should be closed, promise resolved, successUrl opened (and opened from what, your browser, or only window open after closing trustly activity), success event emit from your SDK

**Comment by rhorno** [comment]
Okay, so you are still not getting your alert in the success event? Not sure I understand what and how you want us to describe

**Comment by expcapitaldev** [comment]
@rhorno  
so you are still not getting your alert in the success event? - yes, I do not getting alert in the success event after successful deposit, I sent screen where I remove successUrl from server side (without redirect)

pls provide your repo (where you attached video)

pls describe for example next steps:
a) successUrl/failUrl set for server side  https://www.trustly.net/developer-portal-2?part=selectaccount
1. successdeposit
2. open your screen with confirmation
![image](https://user-images.githubusercontent.com/19390317/127355936-9d531837-a0a8-4c40-bb80-d3b6a76f90c7.png)
3. onTrustlyCheckoutSuccess triggered (for ios/android similar method)
4.  your trustly activity closed after "finish()" method
5. promise resolved (promise().then(()=> "here!!!"))

pls confirm expected steps from your side, and pls describe too if successUrl/failUrl set (  https://www.trustly.net/developer-portal-2?part=selectaccount)
